esphome:
  name: somfy-rts
  name_add_mac_suffix: false
  libraries:
    - EEPROM
    - legion2/Somfy_Remote_Lib@0.4.1
  includes:
    - somfy_arduino_cover.h

esp8266:
  board: d1_mini

logger:

wifi:
  ap:
  use_address: "" # to benefit from name_add_mac_suffix
captive_portal:
improv_serial:

web_server:
  ota: false
  local: true
  css_url: ""
  js_url: ""

api:

cover:
  - platform: custom
    lambda: |-
      EEPROM.begin(32);
      auto somfy_remote = new SomfyArduinoRemote(D1, 16);
      App.register_component(somfy_remote);
      return somfy_remote->covers;
    covers:
      - id: "cover_01"
        name: "Cover 01"
      - id: "cover_02"
        name: "Cover 02"
      - id: "cover_03"
        name: "Cover 03"
      - id: "cover_04"
        name: "Cover 04"
      - id: "cover_05"
        name: "Cover 05"
      - id: "cover_06"
        name: "Cover 06"
      - id: "cover_07"
        name: "Cover 07"
      - id: "cover_08"
        name: "Cover 08"
      - id: "cover_09"
        name: "Cover 09"
      - id: "cover_10"
        name: "Cover 10"
      - id: "cover_11"
        name: "Cover 11"
      - id: "cover_12"
        name: "Cover 12"
      - id: "cover_13"
        name: "Cover 13"
      - id: "cover_14"
        name: "Cover 14"
      - id: "cover_15"
        name: "Cover 15"
      - id: "cover_16"
        name: "Cover 16"

button:
  - platform: factory_reset
    name: Factory reset
  - platform: template
    name: "Cover 01 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_01))->program();
  - platform: template
    name: "Cover 02 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_02))->program();
  - platform: template
    name: "Cover 03 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_03))->program();
  - platform: template
    name: "Cover 04 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_04))->program();
  - platform: template
    name: "Cover 05 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_05))->program();
  - platform: template
    name: "Cover 06 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_06))->program();
  - platform: template
    name: "Cover 07 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_07))->program();
  - platform: template
    name: "Cover 08 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_08))->program();
  - platform: template
    name: "Cover 09 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_09))->program();
  - platform: template
    name: "Cover 10 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_10))->program();
  - platform: template
    name: "Cover 11 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_11))->program();
  - platform: template
    name: "Cover 12 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_12))->program();
  - platform: template
    name: "Cover 13 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_13))->program();
  - platform: template
    name: "Cover 14 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_14))->program();
  - platform: template
    name: "Cover 15 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_15))->program();
  - platform: template
    name: "Cover 16 Prog"
    entity_category: config
    icon: "mdi:wrench"
    on_press:
      - lambda: |-
          ((SomfyArduinoCover*)id(cover_16))->program();
